/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  darkMode: 'class',
  theme: {
    fontFamily: {
      sans: [
        'system-ui',
        '"Segoe UI"',
        'Tahoma',
        '"Noto Sans Arabic"',
        'Roboto',
        'sans-serif',
      ],
    },
    extend: {
      colors: {
        primary: 'var(--primary)',
        'primary-deep': 'var(--primary-deep)',
        'primary-mild': 'var(--primary-mild)',
        'primary-subtle': 'var(--primary-subtle)',
        error: 'var(--error)',
        'error-subtle': 'var(--error-subtle)',
        success: 'var(--success)',
        'success-subtle': 'var(--success-subtle)',
        info: 'var(--info)',
        'info-subtle': 'var(--info-subtle)',
        warning: 'var(--warning)',
        'warning-subtle': 'var(--warning-subtle)',
        neutral: 'var(--neutral)',
        'gray-50': 'var(--gray-50)',
        'gray-100': 'var(--gray-100)',
        'gray-200': 'var(--gray-200)',
        'gray-300': 'var(--gray-300)',
        'gray-400': 'var(--gray-400)',
        'gray-500': 'var(--gray-500)',
        'gray-600': 'var(--gray-600)',
        'gray-700': 'var(--gray-700)',
        'gray-800': 'var(--gray-800)',
        'gray-900': 'var(--gray-900)',
        'gray-950': 'var(--gray-950)',
      },
    },
  },
  plugins: [],
};
